Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
Compiler: /usr/local/cuda-10.1/bin/nvcc 
Build flags: 
Id flags:  -v;--keep;--keep-dir;tmp

The output was:
1
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda-10.1/bin
#$ _THERE_=/usr/local/cuda-10.1/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/ppc64le-linux
#$ TOP=/usr/local/cuda-10.1/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-10.1/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda-10.1/bin/../lib:/usr/local/cuda-10.1/lib64:/home/yxf281/.conda/envs/my_ml_py36/cuda/lib::/home/yxf281/.conda/envs/my_ml_py36/lib/python3.6/site-packages/tensorflow_core
#$ PATH=/usr/local/cuda-10.1/bin/../nvvm/bin:/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/bin:/opt/at12.0/bin:/opt/at12.0/sbin:/home/yxf281/.conda/envs/my_ml_py36/bin:/share/apps/ibm_wml_ce/1.6.2/anaconda3/condabin:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/etc:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-ppc64le/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/bin:/usr/lpp/mmfs/bin:/opt/ibm/jre/bin:/home/yxf281/.local/bin:/home/yxf281/bin
#$ INCLUDES="-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"  
#$ LIBRARIES=  "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib/stubs" "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ rm tmp/a_dlink.reg.c
#$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=105 -include "cuda_runtime.h" "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii" 
#$ cicc --c++14 --gnu_version=80301 --allow_managed --unsigned_chars   -arch compute_30 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library "/usr/local/cuda-10.1/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name "CMakeCUDACompilerId.cu" --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name "tmp/CMakeCUDACompilerId.cudafe1.gpu"  "tmp/CMakeCUDACompilerId.cpp1.ii" -o "tmp/CMakeCUDACompilerId.ptx"
/opt/at12.0/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/opt/at12.0/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

2 errors detected in the compilation of "tmp/CMakeCUDACompilerId.cpp1.ii".
# --error 0x1 --


Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
Compiler: /usr/local/cuda-10.1/bin/nvcc 
Build flags: 
Id flags:  -v;--keep;--keep-dir;tmp

The output was:
1
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda-10.1/bin
#$ _THERE_=/usr/local/cuda-10.1/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/ppc64le-linux
#$ TOP=/usr/local/cuda-10.1/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-10.1/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda-10.1/bin/../lib:/usr/local/cuda-10.1/lib64:/home/yxf281/.conda/envs/my_ml_py36/cuda/lib::/home/yxf281/.conda/envs/my_ml_py36/lib/python3.6/site-packages/tensorflow_core
#$ PATH=/usr/local/cuda-10.1/bin/../nvvm/bin:/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/bin:/opt/at12.0/bin:/opt/at12.0/sbin:/home/yxf281/.conda/envs/my_ml_py36/bin:/share/apps/ibm_wml_ce/1.6.2/anaconda3/condabin:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/etc:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-ppc64le/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/bin:/usr/lpp/mmfs/bin:/opt/ibm/jre/bin:/home/yxf281/.local/bin:/home/yxf281/bin
#$ INCLUDES="-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"  
#$ LIBRARIES=  "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib/stubs" "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ rm tmp/a_dlink.reg.c
#$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=105 -include "cuda_runtime.h" "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii" 
#$ cicc --c++14 --gnu_version=80301 --allow_managed --unsigned_chars   -arch compute_30 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library "/usr/local/cuda-10.1/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name "CMakeCUDACompilerId.cu" --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name "tmp/CMakeCUDACompilerId.cudafe1.gpu"  "tmp/CMakeCUDACompilerId.cpp1.ii" -o "tmp/CMakeCUDACompilerId.ptx"
/opt/at12.0/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/opt/at12.0/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

2 errors detected in the compilation of "tmp/CMakeCUDACompilerId.cpp1.ii".
# --error 0x1 --


Determining if the CUDA compiler works failed with the following output:
Change Dir: /home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_1fb5f/fast 
/usr/bin/gmake -f CMakeFiles/cmTC_1fb5f.dir/build.make CMakeFiles/cmTC_1fb5f.dir/build
gmake[1]: Entering directory `/home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp'
Building CUDA object CMakeFiles/cmTC_1fb5f.dir/main.cu.o
/usr/local/cuda-10.1/bin/nvcc     -x cu -c /home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_1fb5f.dir/main.cu.o
/opt/at12.0/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/opt/at12.0/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

2 errors detected in the compilation of "/tmp/tmpxft_0002633d_00000000-6_main.cpp1.ii".
gmake[1]: *** [CMakeFiles/cmTC_1fb5f.dir/main.cu.o] Error 1
gmake[1]: Leaving directory `/home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_1fb5f/fast] Error 2


Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
Compiler: /usr/local/cuda-10.1/bin/nvcc 
Build flags: 
Id flags:  -v;--keep;--keep-dir;tmp

The output was:
1
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda-10.1/bin
#$ _THERE_=/usr/local/cuda-10.1/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/ppc64le-linux
#$ TOP=/usr/local/cuda-10.1/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-10.1/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda-10.1/bin/../lib:/usr/local/cuda-10.1/lib64:/home/yxf281/.conda/envs/my_ml_py36/cuda/lib::/home/yxf281/.conda/envs/my_ml_py36/lib/python3.6/site-packages/tensorflow_core
#$ PATH=/usr/local/cuda-10.1/bin/../nvvm/bin:/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/bin:/opt/at12.0/bin:/opt/at12.0/sbin:/home/yxf281/.conda/envs/my_ml_py36/bin:/share/apps/ibm_wml_ce/1.6.2/anaconda3/condabin:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/etc:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-ppc64le/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/bin:/usr/lpp/mmfs/bin:/opt/ibm/jre/bin:/home/yxf281/.local/bin:/home/yxf281/bin
#$ INCLUDES="-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"  
#$ LIBRARIES=  "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib/stubs" "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ rm tmp/a_dlink.reg.c
#$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=105 -include "cuda_runtime.h" "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii" 
#$ cicc --c++14 --gnu_version=80301 --allow_managed --unsigned_chars   -arch compute_30 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library "/usr/local/cuda-10.1/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name "CMakeCUDACompilerId.cu" --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name "tmp/CMakeCUDACompilerId.cudafe1.gpu"  "tmp/CMakeCUDACompilerId.cpp1.ii" -o "tmp/CMakeCUDACompilerId.ptx"
/opt/at12.0/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/opt/at12.0/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

2 errors detected in the compilation of "tmp/CMakeCUDACompilerId.cpp1.ii".
# --error 0x1 --


Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
Compiler: /usr/local/cuda-10.1/bin/nvcc 
Build flags: 
Id flags:  -v;--keep;--keep-dir;tmp

The output was:
1
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda-10.1/bin
#$ _THERE_=/usr/local/cuda-10.1/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/ppc64le-linux
#$ TOP=/usr/local/cuda-10.1/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-10.1/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda-10.1/bin/../lib:/usr/local/cuda-10.1/lib64:/home/yxf281/.conda/envs/my_ml_py36/cuda/lib::/home/yxf281/.conda/envs/my_ml_py36/lib/python3.6/site-packages/tensorflow_core
#$ PATH=/usr/local/cuda-10.1/bin/../nvvm/bin:/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/bin:/opt/at12.0/bin:/opt/at12.0/sbin:/home/yxf281/.conda/envs/my_ml_py36/bin:/share/apps/ibm_wml_ce/1.6.2/anaconda3/condabin:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/etc:/opt/ibm/lsfsuite/lsf/10.1/linux3.10-glibc2.17-ppc64le/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/bin:/opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-ppc64le/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/bin:/usr/lpp/mmfs/bin:/opt/ibm/jre/bin:/home/yxf281/.local/bin:/home/yxf281/bin
#$ INCLUDES="-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"  
#$ LIBRARIES=  "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib/stubs" "-L/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ rm tmp/a_dlink.reg.c
#$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-I/usr/local/cuda-10.1/bin/../targets/ppc64le-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=105 -include "cuda_runtime.h" "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii" 
#$ cicc --c++14 --gnu_version=80301 --allow_managed --unsigned_chars   -arch compute_30 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library "/usr/local/cuda-10.1/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name "CMakeCUDACompilerId.cu" --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name "tmp/CMakeCUDACompilerId.cudafe1.gpu"  "tmp/CMakeCUDACompilerId.cpp1.ii" -o "tmp/CMakeCUDACompilerId.ptx"
/opt/at12.0/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/opt/at12.0/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

2 errors detected in the compilation of "tmp/CMakeCUDACompilerId.cpp1.ii".
# --error 0x1 --


Determining if the CUDA compiler works failed with the following output:
Change Dir: /home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_45d1a/fast 
/usr/bin/gmake -f CMakeFiles/cmTC_45d1a.dir/build.make CMakeFiles/cmTC_45d1a.dir/build
gmake[1]: Entering directory `/home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp'
Building CUDA object CMakeFiles/cmTC_45d1a.dir/main.cu.o
/usr/local/cuda-10.1/bin/nvcc     -x cu -c /home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_45d1a.dir/main.cu.o
/opt/at12.0/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/opt/at12.0/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

2 errors detected in the compilation of "/tmp/tmpxft_00026380_00000000-6_main.cpp1.ii".
gmake[1]: *** [CMakeFiles/cmTC_45d1a.dir/main.cu.o] Error 1
gmake[1]: Leaving directory `/home/yxf281/o3d-sem3d/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_45d1a/fast] Error 2


